# -*- coding: utf-8 -*-

from odoo import models, fields, api, _
from odoo.exceptions import UserError
import requests


class CustomMattermost(models.Model):
    _inherit = "stock.picking"

    def sent_stock_webhooks(self):
        # get data picking
        picking_name = self.name
        picking_move_lines = self.move_lines
        result_of_products = ""
        num = 1
        for products in picking_move_lines:
            result_of_products += (
                str(num)
                + ". "
                + products.name
                + " | Qty : "
                + str(products.quantity_done)
                + "\n"
            )
            num += 1

        # get data purchase order from picking
        purchase_id = self.purchase_id
        purchase_order = purchase_id.name
        internal_notes = purchase_id.x_status

        # sending hooks to mattermosst from odoo,
        # hooks already created in mattermost channnel / integrations generated by a link.
        headers = {
            "Content-Type": "application/json",
        }
        values = (
            '{ "text": "['
            + str(purchase_order)
            + "] -- sudah dilakukan penerimaan dengan nomor RO / Picking : "
            + str(picking_name)
            + "\nInternal Notes : "
            + str(internal_notes)
            + "\nProducts diterima :"
            + "\n"
            + str(result_of_products)
            + ' "}'
        )
        hooks = "https://unbiased-titmouse-first.ngrok-free.app/hooks/zwu5qhqkzbdgbfhojyz3xxegue"
        response = requests.post(url=hooks, headers=headers, data=values, verify=False)

        # response, if 200 == success then pop up rainbow man notification
        if response.status_code == 200:
            notification = {
                "effect": {
                    "fadeout": "slow",
                    "message": "Pesan sudah terkirim ke Mattermost",
                    "type": "rainbow_man",
                }
            }
            return notification
        # response if !200 then pop up error notification
        else:
            error_message = (
                "Pesan tidak terkirim error:" + str(response.status_code) + ""
            )
            raise UserError(_(error_message))
