# -*- coding: utf-8 -*-

from odoo import models, fields, api, _
from odoo.exceptions import UserError
import requests
import re


class CustomMattermost(models.Model):
    _inherit = "stock.picking"

    def check_symbols(self, input_string):
        # Use a regular expression to remove all non-alphanumeric characters except [], ., and -
        clean_string = re.sub(r"[^a-zA-Z0-9\s\[\].-]", "", input_string)
        return clean_string

    def sent_stock_webhooks(self):
        # get data picking
        picking_name = self.name
        picking_move_lines = self.move_lines
        warehouse_name = self.location_dest_id.location_id.name
        result_of_products = ""

        for products in picking_move_lines:
            product_name = self.check_symbols(products.name)
            result_of_products += (
                product_name + " | Qty : " + str(int(products.quantity_done)) + "\n"
            )

        # get data purchase order from picking
        purchase_id = self.purchase_id
        purchase_order = purchase_id.name
        vendor_name = purchase_id.partner_id.name
        internal_notes = purchase_id.x_internal_notes

        # sending hooks to mattermosst from odoo,
        # hooks already created in mattermost channnel / integrations generated by a link.
        headers = {
            "Content-Type": "application/json",
        }

        values = (
            '{ "text": "### '
            + str(purchase_order)
            + "\n**Vendor** : "
            + str(vendor_name)
            + "\n**Warehouse** : "
            + str(warehouse_name)
            + "\n**Interal Notes** :\n\n"
            + str(internal_notes)
            + "\n @ariel"
            + "\n\n :white_check_mark: **"
            + str(picking_name)
            + "**"
            + "\n Products diterima :"
            + "\n```\n"
            + str(result_of_products)
            + "\n```"
            + ' "}'
        )

        hooks = "https://unbiased-titmouse-first.ngrok-free.app/hooks/zwu5qhqkzbdgbfhojyz3xxegue"
        response = requests.post(url=hooks, headers=headers, data=values, verify=False)

        # response, if 200 == success then pop up rainbow man notification
        if response.status_code == 200:
            notification = {
                "effect": {
                    "fadeout": "slow",
                    "message": "Pesan sudah terkirim ke Mattermost",
                    "type": "rainbow_man",
                }
            }
            return notification
        # response if !200 then pop up error notification
        else:
            error_message = (
                "Pesan tidak terkirim error:" + str(response.status_code) + ""
            )
            raise UserError(_(error_message))
