# -*- coding: utf-8 -*-

from odoo import models, fields, api, _
from odoo.exceptions import UserError
import requests


class CustomMattermost(models.Model):
    _inherit = "stock.picking"

    def sent_stock_webhooks(self):
        # get data picking
        picking_name = self.name

        # get data purchase order from picking
        purchase_id = self.purchase_id
        purchase_order = purchase_id.name

        # sending hooks to mattermosst from odoo,
        # hooks already created in mattermost channnel / integrations generated by a link.
        headers = {
            "Content-Type": "application/json",
        }
        values = (
            '{ "text": "['
            + str(purchase_order)
            + "] -- sudah dilakukan penerimaan dengan nomor RO / Picking : "
            + str(picking_name)
            + ' "}'
        )
        hooks = "https://unbiased-titmouse-first.ngrok-free.app/hooks/zwu5qhqkzbdgbfhojyz3xxegue"
        response = requests.post(url=hooks, headers=headers, data=values, verify=False)

        # response, if 200 == success then pop up rainbow man notification
        if response.status_code == 200:
            notification = {
                "effect": {
                    "fadeout": "slow",
                    "message": "Pesan sudah terkirim ke Mattermost",
                    "type": "rainbow_man",
                }
            }
            return notification
        # response if !200 then pop up error notification
        else:
            error_message = (
                "Pesan tidak terkirim error:" + str(response.status_code) + ""
            )
            raise UserError(_(error_message))
